name": "LG ESS"
version: "0.0.1"
description: LG ESS for Hassio
slug: LG ESS
url: https://github.com/buktahula/hassio-addons/LG
startup: services
boot: manual
init: false
arch: 
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
