---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.9
  amd64: ghcr.io/home-assistant/amd64-base-python:3.9
  armhf: ghcr.io/home-assistant/armhf-base-python:3.9
  armv7: ghcr.io/home-assistant/armv7-base-python:3.9
  i386: ghcr.io/home-assistant/i386-base-python:3.9
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  PYESS_VERSION: 0.1.14
