name: LG ESS
version: dev
description: LG ESS for Hassio
slug: lg_ess
url: https://github.com/buktahula/hassio-addons/LG
init: false
arch: 
 - aarch64
startup: before
hassio_api: true
MQTT_HOST=$(bashio::services mqtt "host")
MQTT_USER=$(bashio::services mqtt "username")
MQTT_PASSWORD=$(bashio::services mqtt "password")
