name: LG ESS
version: dev
description: LG ESS for Hassio
slug: lg_ess
url: https://github.com/Buktahula/hassio-addons/tree/master/LG_ESS
init: false
arch: 
 - aarch64
startup: before
hassio_api: true
options:
 - MQTT_HOST=$(bashio::services mqtt "host")
 - MQTT_USER=$(bashio::services mqtt "username")
 - MQTT_PASSWORD=$(bashio::services mqtt "password")
